export const routerData = [
  {
    id: 100,
    parentId: null,
    funcName: "信息管理",
    funcImg: "ApartmentOutlined",
    description: "manage",
    childsList: [
      {
        id: 100100,
        parentId: 100,
        funcName: "图像采集",
        funcImg: "DesktopOutlined",
        description: "h_manage",
      },
      {
        id: 100200,
        parentId: 100,
        funcName: "监控管理",
        funcImg: "CameraOutlined",
        description: "d_manage",
        // childsList: [
        //   {
        //     id: 5014,
        //     parentId: 5009,
        //     childsList: [],
        //     funcName: "新增",
        //     funcCode: "010",
        //     funcImg: "",
        //     funcType: 2,
        //     status: 1,
        //     sort: 1,
        //     privilege: 1,
        //     description: "add",
        //   },
        //   {
        //     id: 5015,
        //     parentId: 5009,
        //     childsList: [],
        //     funcName: "编辑",
        //     funcCode: "011",
        //     funcImg: "",
        //     funcType: 2,
        //     status: 1,
        //     sort: 2,
        //     privilege: 1,
        //     description: "edit",
        //   },
        // ],
      },
      {
        id: 100300,
        parentId: 100,
        funcName: "用户管理",
        funcImg: "UserOutlined",
        description: "u_manage",
      },
      {
        id: 100400,
        parentId: 100,
        funcName: "操作日志",
        funcImg: "SolutionOutlined",
        description: "o_log",
      },
    ],
  },
];
